service: notes-app-api

plugins:
    - serverless-webpack

custom:
    webpackIncludeModules: true

provider:
    name: aws
    runtime: nodejs6.10
    stage: prod
    region: us-west-2
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
    create:
        handler: create.main
        events:
            - http:
                path: notes
                method: post
                cors: true
                authorizer:
                    arn: arn:aws:cognito-idp:us-west-2:655205504557:userpool/us-west-2_pdeQDEDo4

    get:
        handler: get.main
        events:
            - http:
                path: notes/{id}
                method: get
                cors: true
                authorizer:
                    arn: arn:aws:cognito-idp:us-west-2:655205504557:userpool/us-west-2_pdeQDEDo4

    list:
        handler: list.main
        events:
            - http:
                path: notes
                method: get
                cors: true
                authorizer:
                    arn: arn:aws:cognito-idp:us-west-2:655205504557:userpool/us-west-2_pdeQDEDo4

    update:
        handler: update.main
        events:
            - http:
                path: notes/{id}
                method: put
                cors: true
                authorizer:
                    arn: arn:aws:cognito-idp:us-west-2:655205504557:userpool/us-west-2_pdeQDEDo4

    delete:
        handler: delete.main
        events:
            - http:
                path: notes/{id}
                method: delete
                cors: true
                authorizer:
                    arn: arn:aws:cognito-idp:us-west-2:655205504557:userpool/us-west-2_pdeQDEDo4
