service: notes-app-api

plugins:
    - serverless-webpack

custom:
    webpackIncludeModules: true

provider:
    name: aws
    runtime: nodejs6.10
    stage: prod
    region: us-west-2
    iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
    notes-create:
        handler: notes-create.main
        events:
            - http:
                path: notes
                method: post
                cors: true
                authorizer: aws_iam

    notes-get:
        handler: notes-get.main
        events:
            - http:
                path: notes/{id}
                method: get
                cors: true
                authorizer: aws_iam

    notes-list:
        handler: notes-list.main
        events:
            - http:
                path: notes
                method: get
                cors: true
                authorizer: aws_iam

    notes-update:
        handler: notes-update.main
        events:
            - http:
                path: notes/{id}
                method: put
                cors: true
                authorizer: aws_iam

    notes-delete:
        handler: notes-delete.main
        events:
            - http:
                path: notes/{id}
                method: delete
                cors: true
                authorizer: aws_iam
